[package]
name = "wm-builtin"
version = "0.0.0"
description = "Embedded builtin binaries for GlazeWM"
edition = "2021"

[build-dependencies]
anyhow = { workspace = true }

[dependencies]
anyhow = { workspace = true }
home = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
  "Win32_Foundation",
  "Win32_System_Threading",
  "Win32_System_Diagnostics_ToolHelp",
] }

[features]
# Enable building zebar from source (requires pnpm and node)
build_zebar = []
